### ISSUE TITLE
eplanner.py astropy4

### ISSUE THREAD

**Issue by paulkerry1** [trmrsh/trm-observing#4]
Using eplanner.py with astropy==4.0.1.post1 stops with an error

eplanner.py targets.lis NTT targets.prg 2020-05-05
<output snipped>
Sun is at alt=-0.25 at 2020-05-05 22:02 and 2020-05-06 11:17
Sun is at alt=-10.0 at 2020-05-05 22:49 and 2020-05-06 10:30
Sun is at alt=-15.0 at 2020-05-05 23:12 and 2020-05-06 10:06
Traceback (most recent call last):
  File "/usr/local/bin/eplanner.py", line 510, in <module>
    times += times.light_travel_time(star.position)
  File "/usr/local/lib/python3.7/dist-packages/astropy/time/core.py", line 1212, in light_travel_time
    raise ValueError('An EarthLocation needs to be set or passed '
ValueError: An EarthLocation needs to be set or passed in to calculate bary- or heliocentric corrections

The same eplanner.py command works perfectly with astropy==3.2.3

Cheers
Paul

**Comment by paulkerry1** [comment]
Fixed with trm-observing version 1.0.3

Cheers
Paul
